language: ruby
rvm:
- 2.2
#script: bundle exec jekyll build && bundle exec htmlproof ./_site
script: bundle exec jekyll build --future


# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

install:
- travis_retry npm install
- travis_retry bower install
- travis_retry bundle install
