---
# Site wide configuration
title: "Simeon Pashley"
description: "Personal website"
logo: site-logo.png
teaser: default-teaser.png
locale: en_GB
words_per_minute: 200
title_separator: "Ã—"
url: http://www.pashley.org
shortname: pashley.org

# Site owner
authors:
  gamelinchpin:
    name:       Simeon Pashley
    email:      ""
    position:   ""
    start_date: 1986-02-01
    github:     gamelinchpin
    twitter:    simeonpashley
    gplus:      +SimeonPashley
    linkedin:   https://uk.linkedin.com/in/simeonpashley/
    gravatar:   e75deb5e1dc8de89fecefba23a1efd97
    about:      ""

owner:
  name: "Simeon Pashley"
  email: ""
  twitter: simeonpashley
  github: gamelinchpin
  gplus: +SimeonPashley
  gravatar:
    hash: e75deb5e1dc8de89fecefba23a1efd97
    img_src: "https://www.gravatar.com/avatar/e75deb5e1dc8de89fecefba23a1efd97?s=200"
  linkedin_url: https://uk.linkedin.com/in/simeonpashley/
  github-repo: https://github.com/gamelinchpin/gamelinchpin.github.io
  google:
    ad-client: ca-pub-7328585512091257
    ad-slot:
    analytics: UA-16937664-6
    plus: https://plus.google.com/+SimeonPashley/posts
  bing:
    verify: D81F4C18A6CB3018F64D7C827D953DFD
  alexa:
    verify: Y5DYjZ4VWlrQzBP5kcQJeOKLNas
  yandex:
    verify: 55a5419baf76a498
  bio: "Just another."
  avatar: bio-photo.jpg # 160x160 px image for author byline

# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data

# Handling Reading
safe:         false
include:
  - ".htaccess"
  - '_pages'
exclude:
  - README.md
  - package.json
  - gruntfile.js
  - sass/
  - vendor
  - _posts/older
keep_files:
  - ".git"
  - ".svn"
  - images

encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-archives
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jemoji
  - jekyll-paginate

# Conversion
markdown:          kramdown
highlighter:       rouge
lsi:               true
excerpt_separator: <!-- more -->

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     /:year/:month/:title
paginate:      10
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  hard_wrap:      false
  entity_output:  as_char
  toc_levels:     1..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Site settings

twitter_username: simeonpashley
github_username:  gamelinchpin

# Collections

collections:
  faqs:
    output:    true
    permalink: /:collection/:path/
    title:     FAQs
  components:
    output: false
  colors:
    output: false

defaults:
  - scope:
      path: "_posts/articles"
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout:   article
      category: articles
  - scope:
      path: "_posts/projects"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout:   project # overrides previous default layout
      category: projects
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: article

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Plugin: jekyll-archives

jekyll-archives:
  enabled: [year, month, tags]
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: /tag/:name/
  layouts:
    year: year-archive
    month: month-archive
    tag: tag_index
    #day: day-archive
    #tag: tag-archive-layout
